---- Base app schema

-- User
-- Local mirror of the identity SuperTokens core owns. No password or
-- session token is stored here — SuperTokens core (Postgres, separate
-- schema) owns those. This table exists for app-specific profile data and
-- so other Farklin services can join on a stable internal id.
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  st_user_id varchar(36) NOT NULL UNIQUE, -- SuperTokens userId (uuid)
  email varchar(256) NOT NULL UNIQUE,
  typ user_typ NOT NULL DEFAULT 'User',

  -- Login risk baseline (see lib_auth::risk) — what this user's last
  -- *successful* login looked like, compared against on the next signin.
  -- Both changing together is what login-risk.json blocks on. Null on a
  -- brand new user: nothing to compare the first login against yet.
  last_ip varchar(45), -- long enough for IPv6
  last_visitor_id varchar(64), -- FingerprintJS visitorId

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);
