---- Base app schema

-- User
-- Local mirror of the identity SuperTokens core owns. No password or
-- session token is stored here — SuperTokens core (Postgres, separate
-- schema) owns those. This table exists for app-specific profile data and
-- so other Farklin services can join on a stable internal id.
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  st_user_id varchar(36) NOT NULL UNIQUE, -- SuperTokens userId (uuid)
  email varchar(256) NOT NULL UNIQUE,
  typ user_typ NOT NULL DEFAULT 'User',

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);
