-- No static seed rows: a `user` row is only valid alongside a real
-- SuperTokens account (st_user_id must reference one). Seed dev users by
-- calling POST /api/signup against this running service instead, or use
-- `lib_core::_dev_utils::seed_user` in tests after calling
-- `lib_auth::supertokens::sign_up`.
